import json
from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from app.schemas import ChatRequest, ChatResponse
from app.services.rag_services import answer_question
from app.rag_pipeline.retrieval import PolicyRAGPipeline

pipeline = PolicyRAGPipeline()

router = APIRouter(prefix = "/chat", tags = ["chat"])

@router.post("/query", response_model = ChatResponse)
async def chat_query(request : ChatRequest):
    return await answer_question(request.question, pipeline)

@router.post("/stream")
async def chat_stream(request : ChatRequest):
    async def event_stream():

        # Iterate over the tokens generated by the RAG pipeline.
        # async for keeps the generator on the event-loop thread —
        # no thread-pool bounce, so tracing context stays intact.
        async for item in pipeline.stream_answer(request.question):
            event_type = item["type"]    

            # Filtering out the "type" key from the payload to avoid duplication
            payload = {key:value for key, value in item.items() if key != "type"}

            # Emits the event type and the corresponding payload in SSE format
            yield f"event: {event_type}\n"
            yield f"data: {json.dumps(payload)}\n\n"
  
    # Return a streaming SSE response
    return StreamingResponse(event_stream(), media_type="text/event-stream")