import json
from fastapi import APIRouter, Request
from fastapi.responses import StreamingResponse, Response, JSONResponse
from app.schemas import ChatRequest, ChatResponse
from app.services.rag_services import answer_question
from app.rag_pipeline.retrieval import PolicyRAGPipeline
from app.services import storage_service
from pydantic import BaseModel

pipeline = PolicyRAGPipeline()

router = APIRouter(prefix = "/chat", tags = ["chat"])


class FileUrlRequest(BaseModel):
    file_path: str


@router.post("/file-url")
async def get_file_url(req: FileUrlRequest):
    """Get a fresh signed URL for a file in Supabase storage.
    Used by the chat frontend to open PDF/markdown files on click."""
    try:
        # Determine storage path: try PDF version first for markdown files
        file_path = req.file_path
        ext = file_path.rsplit(".", 1)[-1].lower() if "." in file_path else ""
        if ext == "md":
            base_name = file_path.rsplit(".", 1)[0]
            pdf_path = f"pdfs/{base_name}.pdf"
            if storage_service.file_exists(pdf_path):
                file_path = pdf_path
        
        url = storage_service.create_signed_url(file_path, expires_in=3600)
        return JSONResponse({"url": url, "file_path": file_path})
    except Exception as e:
        return JSONResponse({"error": str(e)}, status_code=500)


@router.options("/stream")
async def chat_stream_options():
    """Handle CORS preflight for the streaming endpoint."""
    return Response(status_code=200)


@router.post("/query", response_model = ChatResponse)
async def chat_query(request : ChatRequest):
    return answer_question(request.question, pipeline);    

@router.post("/stream")
async def chat_stream(request : ChatRequest):
    def event_stream():
        try:
            # Iterate over the tokens generated by the RAG pipeline
            for item in pipeline.stream_answer(request.question):
                event_type = item["type"]    

                # Filtering out the "type" key from the payload to avoid duplication
                payload = {key:value for key, value in item.items() if key != "type"}

                # Combine event + data into a single yield to prevent
                # Starlette thread-queue overflow (ERR_INCOMPLETE_CHUNKED_ENCODING)
                yield f"event: {event_type}\ndata: {json.dumps(payload)}\n\n"
        except Exception as e:
            import traceback
            error_msg = f"Stream error: {e}"
            print(f"[chat/stream ERROR] {error_msg}")
            traceback.print_exc()
            yield f"event: error\ndata: {json.dumps({'message': error_msg})}\n\n"
  
    # Return a streaming SSE response with keep-alive headers
    return StreamingResponse(
        event_stream(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        },
    )